# Generated by Django 4.1 on 2024-06-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_send',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('crucial', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'News',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SummarizeNews',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='newApp.news')),
                ('first_sentence', models.TextField(blank=True, null=True)),
                ('second_sentence', models.TextField(blank=True, null=True)),
                ('third_sentence', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Summarize_news',
                'managed': False,
            },
        ),
    ]
