# Generated by Django 4.2.13 on 2024-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='info',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
