# Generated by Django 4.2.13 on 2024-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_news_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
