# Generated by Django 4.1 on 2024-06-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_usersend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True},
        ),
    ]
