# Generated by Django 4.2.13 on 2024-06-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
