# Generated by Django 4.2.13 on 2024-06-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_gpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpt',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='output_tokens',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='total_tokens',
        ),
        migrations.AddField(
            model_name='gpt',
            name='fe_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='fe_input_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='fe_output_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='fe_total_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='su_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='su_input_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='su_output_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gpt',
            name='su_total_tokens',
            field=models.IntegerField(null=True),
        ),
    ]
