# Generated by Django 4.2.13 on 2024-06-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_remove_gpt_cost_remove_gpt_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarizenews',
            options={'managed': True},
        ),
    ]
