# Generated by Django 4.2.13 on 2024-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_alter_summarizenews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizenews',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
