# Generated by Django 4.2.13 on 2024-06-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_summarizenews_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
